# Generated by Django 4.2.2 on 2024-10-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("message", models.TextField(null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
