# Generated by Django 4.2.2 on 2024-10-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("created_date",)},
        ),
    ]
