# Generated by Django 4.2.2 on 2024-10-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("updated_date",)},
        ),
    ]
