# Generated by Django 4.2.2 on 2024-10-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={},
        ),
    ]
