# Generated by Django 4.2.2 on 2024-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("updated_date",)},
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
