# Generated by Django 4.2.2 on 2024-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_contact_options_alter_contact_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="published_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
