# Generated by Django 4.2.2 on 2024-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_contact_published_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("message", models.TextField(null=True)),
            ],
            options={
                "ordering": ("updated_date",),
            },
        ),
    ]
