# Generated by Django 4.2.2 on 2024-10-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_cont"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cont",
        ),
    ]
