# Generated by Django 4.2.2 on 2024-10-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_delete_cont"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="published_date",
        ),
    ]
