# Generated by Django 4.2.2 on 2024-10-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
